Repository jenkinsci/gitea-plugin, pull requests merged in 2021-11, with the labels that each got.

#27 feat: add archived filter (JENKINS-64353)
  .gitignore
  src/main/java/org/jenkinsci/plugin/gitea/ExcludeArchivedRepositoriesTrait.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigatorContext.java
  src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaRepository.java
  src/main/resources/org/jenkinsci/plugin/gitea/ExcludeArchivedTrait/config.jelly
  src/main/resources/org/jenkinsci/plugin/gitea/GiteaSCMNavigator/help.html
  src/main/resources/org/jenkinsci/plugin/gitea/Messages.properties
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnectionTest.java
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection_PagedRequests_Test.java
Labels: enhancement

#24 FIX JENKINS-60017
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSource.java
  src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaVersion.java
Labels: bug

#37 fix(webhook): fix NPE when saving OrganizationFolder using WebhookRegistrationTrait.
  src/main/resources/org/jenkinsci/plugin/gitea/WebhookRegistrationTrait/config.jelly
  src/main/resources/org/jenkinsci/plugin/gitea/WebhookRegistrationTrait/help-mode.html
  src/main/resources/org/jenkinsci/plugin/gitea/WebhookRegistrationTrait/help.html
Labels: bug

#38 fix(webhook): fix that new tags are not discovered automatically via TagDiscoveryTrait and webhooks.
  src/main/java/org/jenkinsci/plugin/gitea/GiteaCreateSCMEvent.java
  src/test/java/org/jenkinsci/plugin/gitea/GiteaCreateSCMEventTest.java
Labels: bug

#42 Bump version to 1.5.0
  pom.xml
Labels: chore

#43 Fix release versioning + incremental builds
  .github/workflows/cd.yaml
  README.md
  pom.xml
Labels: chore

#44 [JENKINS-67068] Fix regression for branch names with slashes
  src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection.java
Labels: bug

#45 Add codestyle checks
  .mvn/checkstyle-suppressions.xml
  .mvn/checkstyle.xml
  pom.xml
  src/main/java/org/jenkinsci/plugin/gitea/ExcludeArchivedRepositoriesTrait.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaDeleteSCMEvent.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaNotifier.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMFileSystem.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigatorContext.java
  src/main/java/org/jenkinsci/plugin/gitea/GiteaWebhookListener.java
  src/main/java/org/jenkinsci/plugin/gitea/SSHCheckoutTrait.java
  src/main/java/org/jenkinsci/plugin/gitea/TagDiscoveryTrait.java
  src/main/java/org/jenkinsci/plugin/gitea/TagSCMRevision.java
  src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaCommitDetail.java
  src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaRepository.java
  src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection.java
  src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnectionFactory.java
  src/main/java/org/jenkinsci/plugin/gitea/client/spi/GiteaConnectionFactory.java
  src/main/java/org/jenkinsci/plugin/gitea/servers/GiteaServer.java
  src/test/java/org/jenkinsci/plugin/gitea/GiteaBrowserTest.java
  src/test/java/org/jenkinsci/plugin/gitea/GiteaCreateSCMEventTest.java
  src/test/java/org/jenkinsci/plugin/gitea/GiteaDeleteSCMEventTest.java
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnectionTest.java
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection_PagedRequests_Test.java
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/GiteaConnection_DisabledPR_Issues.java
  src/test/java/org/jenkinsci/plugin/gitea/client/impl/GiteaConnection_PagedRequests.java
  src/test/java/org/jenkinsci/plugin/gitea/client/mock/MockGiteaConnectionFactory.java
Labels: chore
